name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
[commands]
predev = "node scripts/prisma-with-local-default.mjs generate"
dev = "node scripts/prisma-with-local-default.mjs migrate deploy && npm exec react-router dev"
